name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: When I clicked on ... it didn't ... I expected it to ...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Thor GUI version
      description: What version of Thor GUI are you using? (check in the "About" tab)
      options:
        - Alpha v0.4.0
        - Alpha v0.3.2
        - Alpha v0.3.1
        - Alpha v0.3.0
        - Alpha v0.2.1
        - Alpha v0.2.0
        - Alpha v0.1
        - Alpha v0.0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Thor Flash Utility version
      description: What version of the Thor Flash Utility are you using? (check in the "About" tab)
      options:
        - 1.0.4
        - 1.0.3
        - 1.0.2
        - 1.0.1
        - 1.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Thor GUI's log output 
      description: Please copy and paste Thor GUI's log output from the terminal. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Thor Flash Utility's log output 
      description: Please copy and paste Thor Flash Utility's log output from the "Log" tab. This will be automatically formatted into code, so no need for backticks.
      render: shell
