name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: When I clicked on ... it didn't ... I expected it to ...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Galaxy Flasher version
      description: What version of Thor GUI are you using? (check in the "About" tab)
      options:
        - Alpha v0.5.0
        - Alpha v0.4.6
        - Alpha v0.4.5.1
        - Alpha v0.4.5
        - Alpha v0.4.4
        - Alpha v0.4.3
        - Alpha v0.4.2
        - Alpha v0.4.1
        - Alpha v0.4.0
        - Alpha v0.3.2
        - Alpha v0.3.1
        - Alpha v0.3.0
        - Alpha v0.2.1
        - Alpha v0.2.0
        - Alpha v0.1
        - Alpha v0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Galaxy Flasher's log output 
      description: Please copy and paste Galaxy Flasher's log output from the terminal. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Flash tool's log output 
      description: Please copy and paste the Flash tool's log output from the "Log" tab. This will be automatically formatted into code, so no need for backticks.
      render: shell
