name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Thor GUI version
      description: What version of Thor GUI are you using? (check in the "About" tab)
      options:
        - Alpha v0.3.1
        - Alpha v0.3.0
        - Alpha v0.2.1
        - Alpha v0.2.0
        - Alpha v0.1
        - Alpha v0.0
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Thor version
      description: What version of Thor are you using? (check in the "About" tab)
      options:
        - v1.0.4
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Thor GUI's log output 
      description: Please copy and paste Thor GUI's log output from the terminal. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Thor's log output 
      description: Please copy and paste Thor's log output from the "Log" tab. This will be automatically formatted into code, so no need for backticks.
      render: shell
