name: Feature request
description: Suggest an improvement
labels: ["Enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description:  A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to see in Thor GUI.
      placeholder: Instead of ... Thor GUI should ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe why the feature would be helpful
      description: A description of why this feature would be helpful.
      placeholder: This feature would be helpful because ...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Thor GUI version
      description: What version of Thor GUI are you using? (check in the "About" tab)
      options:
        - Alpha v0.4.0
        - Alpha v0.3.2
        - Alpha v0.3.1
        - Alpha v0.3.0
        - Alpha v0.2.1
        - Alpha v0.2.0
        - Alpha v0.1
        - Alpha v0.0
      default: 0
    validations:
      required: true
